/**
 * METRA-VERIFY Synthetic Mock Data Layer
 * 
 * DISCLAIMER:
 * All records in this file are synthetic demonstrations for SIH 2026 evaluation.
 * They do not represent real government or legal records.
 * AI analysis output is advisory decision-support only; final verification is performed by authorized personnel.
 */

export const MOCK_USERS = {
  pushpendra: {
    id: 'usr_pushpa_01',
    name: 'Pushpendra Singh',
    email: 'PuhspaGOat-singhpushpendra95734@gmail.com',
    username: 'singhpushpendra95734_db_user',
    role: 'business',
    organization: 'Singh Legal Metrology & Enterprise Tech',
    phone: '+91 95734 00000',
    address: 'Plot 24, Cyber Park & Logistics Complex, Sector 18, New Delhi - 110001',
    registrationNumber: 'GSTIN07AAAPS95734Z1',
    licenseNo: '07AAAPS95734Z1',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80'
  },
  business: {
    id: 'usr_biz_01',
    name: 'Rajesh Sharma',
    email: 'rajesh@sharmatraders.com',
    role: 'business',
    organization: 'Sharma Traders & Co.',
    phone: '+91 98765 43210',
    address: 'Shop 42, Central Mandi Market, Sector 18, New Delhi',
    registrationNumber: 'GSTIN07AAACS1429B1Z8',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80'
  },
  inspector: {
    id: 'usr_insp_02',
    name: 'Vikram Singh',
    email: 'vikram.singh@metraverify.internal',
    role: 'inspector',
    badgeNumber: 'INSP-NZ-4082',
    jurisdiction: 'Zone 4 - North Delhi Metro & Industrial Cluster',
    phone: '+91 98111 22334',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80'
  },
  officer: {
    id: 'usr_off_03',
    name: 'Dr. Anita Deshmukh',
    email: 'anita.deshmukh@metraverify.internal',
    role: 'officer',
    designation: 'Authorized Legal Metrology Verification Officer',
    office: 'Directorate of Legal Metrology, State HQ',
    phone: '+91 99200 88776',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80'
  }
};

export const MOCK_INSTRUMENTS = [
  {
    id: 'MV-INS-PS-001',
    uin: 'IND-LM-2026-PS01-95734',
    businessId: 'usr_pushpa_01',
    businessName: 'Singh Legal Metrology & Enterprise Tech',
    ownerName: 'Pushpendra Singh',
    ownerEmail: 'PuhspaGOat-singhpushpendra95734@gmail.com',
    instrumentType: 'Digital Weighing Scale',
    category: 'Non-Automatic Weighing Instrument (NAWI)',
    manufacturer: 'Pushpa Metrology Tech',
    brand: 'Pushpa Metrology Tech',
    model: 'PM-DS-95734 Ultra-Precision',
    modelNo: 'PM-DS-95734 Ultra-Precision',
    serialNumber: 'PS-SN-9573401',
    serialNo: 'PS-SN-9573401',
    capacity: '60 kg',
    maxCapacity: 60,
    minCapacity: 0.1,
    leastCount: 0.002,
    accuracyClass: 'Class III (Medium Accuracy)',
    verificationDivision: 'e = 2 g, d = 0.5 g',
    purchaseDate: '2025-05-10',
    location: 'Main Logistics & Distribution Bay A, Cyber Park, Sector 18, New Delhi',
    installationAddress: 'Main Logistics & Distribution Bay A, Cyber Park, Sector 18, New Delhi',
    lastVerifiedDate: '2026-09-05',
    nextDueCheck: '2027-09-05',
    status: 'VERIFIED',
    activeCertificateId: 'MV-CERT-PS95734-01',
    applicationsCount: 2
  },
  {
    id: 'MV-INS-PS-002',
    uin: 'IND-LM-2026-PS02-95734',
    businessId: 'usr_pushpa_01',
    businessName: 'Singh Legal Metrology & Enterprise Tech',
    ownerName: 'Pushpendra Singh',
    ownerEmail: 'PuhspaGOat-singhpushpendra95734@gmail.com',
    instrumentType: 'Heavy Duty Platform Scale',
    category: 'Industrial Platform Scale',
    manufacturer: 'Pushpa-Apex Metrology Systems',
    brand: 'Pushpa-Apex Metrology Systems',
    model: 'PM-PL-3000 Heavy Master',
    modelNo: 'PM-PL-3000 Heavy Master',
    serialNumber: 'PS-SN-9573402',
    serialNo: 'PS-SN-9573402',
    capacity: '3000 kg',
    maxCapacity: 3000,
    minCapacity: 5,
    leastCount: 0.05,
    accuracyClass: 'Class III (Industrial)',
    verificationDivision: 'e = 50 g, d = 20 g',
    purchaseDate: '2025-08-20',
    location: 'Heavy Freight Terminal & Loading Bay 4, Sector 18, New Delhi',
    installationAddress: 'Heavy Freight Terminal & Loading Bay 4, Sector 18, New Delhi',
    lastVerifiedDate: '2025-09-20',
    nextDueCheck: '2026-09-20',
    status: 'INSPECTION_SCHEDULED',
    activeCertificateId: null,
    applicationsCount: 1
  },
  {
    id: 'MV-INS-PS-003',
    uin: 'IND-LM-2026-PS03-95734',
    businessId: 'usr_pushpa_01',
    businessName: 'Singh Legal Metrology & Enterprise Tech',
    ownerName: 'Pushpendra Singh',
    ownerEmail: 'PuhspaGOat-singhpushpendra95734@gmail.com',
    instrumentType: 'Precision Laboratory Micro-Balance',
    category: 'Fine Chemical Analytical Balance',
    manufacturer: 'Pushpa-Sartorius Ultra-Lab',
    brand: 'Pushpa-Sartorius Ultra-Lab',
    model: 'SRT-PREC-95734 Precision Pro',
    modelNo: 'SRT-PREC-95734 Precision Pro',
    serialNumber: 'PS-SN-9573403',
    serialNo: 'PS-SN-9573403',
    capacity: '500 g',
    maxCapacity: 0.5,
    minCapacity: 0.000001,
    leastCount: 0.0000001,
    accuracyClass: 'Class I (Special High Precision)',
    verificationDivision: 'e = 1 mg, d = 0.1 mg',
    purchaseDate: '2026-01-15',
    location: 'Advanced Calibration & Metrology Cleanroom Lab, New Delhi',
    installationAddress: 'Advanced Calibration & Metrology Cleanroom Lab, New Delhi',
    lastVerifiedDate: null,
    nextDueCheck: '2026-09-25',
    status: 'PENDING_REVIEW',
    activeCertificateId: null,
    applicationsCount: 1
  },
  {
    id: 'MV-INS-PS-004',
    uin: 'IND-LM-2026-PS04-95734',
    businessId: 'usr_pushpa_01',
    businessName: 'Singh Legal Metrology & Enterprise Tech',
    ownerName: 'Pushpendra Singh',
    ownerEmail: 'PuhspaGOat-singhpushpendra95734@gmail.com',
    instrumentType: 'Automatic Checkweigher Belt',
    category: 'Automatic Gravimetric Filling & Checkweighing',
    manufacturer: 'Pushpa-Ishida Dynamic Systems',
    brand: 'Pushpa-Ishida Dynamic Systems',
    model: 'PM-CKW-95734 Dynamic',
    modelNo: 'PM-CKW-95734 Dynamic',
    serialNumber: 'PS-SN-9573404',
    serialNo: 'PS-SN-9573404',
    capacity: '25 kg',
    maxCapacity: 25,
    minCapacity: 0.02,
    leastCount: 0.001,
    accuracyClass: 'Class XIII(1) Automatic',
    verificationDivision: 'e = 1 g, d = 0.2 g',
    purchaseDate: '2025-11-10',
    location: 'Automated High-Speed Packaging Conveyor Line 2, New Delhi',
    installationAddress: 'Automated High-Speed Packaging Conveyor Line 2, New Delhi',
    lastVerifiedDate: '2026-08-15',
    nextDueCheck: '2027-08-15',
    status: 'VERIFIED',
    activeCertificateId: 'MV-CERT-PS95734-04',
    applicationsCount: 1
  },
  {
    id: 'MV-INS-000123',
    businessId: 'usr_biz_01',
    businessName: 'Sharma Traders & Co.',
    ownerName: 'Rajesh Sharma',
    instrumentType: 'Digital Weighing Scale',
    category: 'Non-Automatic Weighing Instrument (NAWI)',
    manufacturer: 'ABC Instruments Ltd.',
    model: 'WS-500 Industrial Precision',
    serialNumber: 'WS123456',
    capacity: '50 kg',
    accuracyClass: 'Class III (Medium Accuracy)',
    verificationDivision: 'e = 5 g, d = 1 g',
    purchaseDate: '2025-04-12',
    location: 'Main Retail Billing Counter - Bay 1, New Delhi',
    lastVerifiedDate: '2025-09-08',
    nextDueCheck: '2027-09-08',
    status: 'VERIFIED',
    activeCertificateId: 'MV-2026-000123',
    applicationsCount: 2
  },
  {
    id: 'MV-INS-000124',
    businessId: 'usr_biz_01',
    businessName: 'Sharma Traders & Co.',
    ownerName: 'Rajesh Sharma',
    instrumentType: 'Heavy Duty Platform Scale',
    category: 'Industrial Platform Scale',
    manufacturer: 'Apex Metrology Systems',
    model: 'APX-PL-1500',
    serialNumber: 'APX992811',
    capacity: '1500 kg',
    accuracyClass: 'Class III (Industrial)',
    verificationDivision: 'e = 200 g',
    purchaseDate: '2024-11-20',
    location: 'Goods Inward Warehouse & Loading Dock B, New Delhi',
    lastVerifiedDate: '2025-08-14',
    nextDueCheck: '2026-08-14',
    status: 'INSPECTION_SCHEDULED',
    activeCertificateId: null,
    applicationsCount: 1
  },
  {
    id: 'MV-INS-000125',
    businessId: 'usr_biz_01',
    businessName: 'Sharma Traders & Co.',
    ownerName: 'Rajesh Sharma',
    instrumentType: 'Precision Laboratory Micro-Balance',
    category: 'Fine Chemical Analytical Balance',
    manufacturer: 'Sartor Instruments',
    model: 'SI-PRECISION-220',
    serialNumber: 'SRT-44021',
    capacity: '220 g',
    accuracyClass: 'Class I (Special High Precision)',
    verificationDivision: 'e = 1 mg, d = 0.1 mg',
    purchaseDate: '2026-01-10',
    location: 'Quality Assurance Testing Chamber, New Delhi',
    lastVerifiedDate: null,
    nextDueCheck: '2026-09-20',
    status: 'PENDING_REVIEW',
    activeCertificateId: null,
    applicationsCount: 1
  },
  {
    id: 'MV-INS-744542',
    uin: 'IND-LM-2026-744542',
    businessId: 'usr_biz_01',
    businessName: 'Apex Commercial Solutions Ltd',
    ownerName: 'Ramesh Kumar',
    ownerEmail: 'ramesh.kumar@apexcommercial.in',
    instrumentType: 'Electronic Bench Scale',
    category: 'Non-Automatic Weighing Instrument (NAWI)',
    manufacturer: 'Apex Metrology Systems',
    brand: 'Apex Metrology Systems',
    model: 'PM-DS-5000 Ultra-Precision',
    modelNo: 'PM-DS-5000 Ultra-Precision',
    serialNumber: 'MT-241786',
    serialNo: 'MT-241786',
    capacity: '30 kg',
    maxCapacity: 30,
    minCapacity: 0.1,
    leastCount: 0.002,
    accuracyClass: 'Class III (Medium Accuracy)',
    verificationDivision: 'e = 2 g, d = 0.5 g',
    purchaseDate: '2026-01-10',
    location: 'Plot 42, Okhla Industrial Area Phase-III, New Delhi - 110020',
    installationAddress: 'Plot 42, Okhla Industrial Area Phase-III, New Delhi - 110020',
    lastVerifiedDate: null,
    nextDueCheck: '2027-09-19',
    status: 'INSPECTION_SCHEDULED',
    activeCertificateId: null,
    applicationsCount: 1
  }
];

export const MOCK_CERTIFICATES = [];

export const MOCK_APPLICATIONS = [
  {
    id: 'MV-APP-438242',
    applicationNo: 'MV-APP-438242',
    instrumentId: 'MV-INS-744542',
    instrumentType: 'Electronic Bench Scale',
    businessId: 'usr_biz_01',
    businessName: 'Apex Commercial Solutions Ltd',
    submissionDate: '2026-09-19',
    createdAt: new Date().toISOString(),
    status: 'INSPECTION_ASSIGNED',
    currentStep: 5,
    assignedInspector: 'Insp. Vikram Sharma (Badge: DL-LM-INS-985)',
    assignedOfficer: 'Dr. Anita Deshmukh',
    certificateId: null,
    riskScore: 14,
    riskLevel: 'LOW',
    slaRemainingDays: 3.0,
    aiScore: 94,
    aiStatus: 'PASSED_ADVISORY',
    aiRemarks: 'Statutory documentation verified. Class III tolerance verified under Rule 18.',
    statutoryFee: {
      amount: '₹2,500.00',
      receiptNo: 'TR-2026-438242',
      status: 'PAID'
    },
    traderDetails: {
      proprietor: 'Ramesh Kumar',
      email: 'ramesh.kumar@apexcommercial.in',
      phone: '+91 98112 34567',
      gstin: '07AAAAA0000A1Z5',
      address: 'Plot 42, Okhla Industrial Area Phase-III, New Delhi - 110020'
    },
    instrumentDetails: {
      category: 'Non-Automatic Weighing Instrument (NAWI)',
      manufacturer: 'Apex Metrology Systems',
      model: 'PM-DS-5000 Ultra-Precision',
      serialNumber: 'MT-241786',
      accuracyClass: 'Class III (Medium Accuracy)',
      maxCapacity: '30 kg',
      minCapacity: '100 g',
      verificationDivision: '2 g (e)',
      installationAddress: 'Plot 42, Okhla Industrial Area Phase-III, New Delhi - 110020'
    },
    instrument: {
      id: 'MV-INS-744542',
      uin: 'IND-LM-2026-744542',
      instrumentType: 'Electronic Bench Scale',
      category: 'Non-Automatic Weighing Instrument (NAWI)',
      manufacturer: 'Apex Metrology Systems',
      model: 'PM-DS-5000 Ultra-Precision',
      serialNumber: 'MT-241786',
      accuracyClass: 'Class III (Medium Accuracy)',
      maxCapacity: 30,
      minCapacity: 0.1,
      leastCount: 0.002,
      location: 'Plot 42, Okhla Industrial Area Phase-III, New Delhi - 110020',
      status: 'UNVERIFIED'
    },
    documents: [
      { name: 'Model_Approval_Cert_Rule18.pdf', size: '2.1 MB', uploadedAt: 'Today', status: 'Verified' },
      { name: 'Purchase_Tax_Invoice.pdf', size: '1.4 MB', uploadedAt: 'Today', status: 'Verified' }
    ]
  }
];

export const MOCK_INSPECTION_ASSIGNMENTS = [
  {
    id: 'INSP-438242',
    applicationId: 'MV-APP-438242',
    instrumentId: 'MV-INS-744542',
    businessId: 'usr_biz_01',
    businessName: 'Apex Commercial Solutions Ltd',
    contactPerson: 'Ramesh Kumar (Proprietor)',
    contactEmail: 'ramesh.kumar@apexcommercial.in',
    businessPhone: '+91 98112 34567',
    instrumentType: 'Electronic Bench Scale',
    category: 'Non-Automatic Weighing Instrument (NAWI)',
    serialNumber: 'MT-241786',
    manufacturer: 'Apex Metrology Systems',
    model: 'PM-DS-5000 Ultra-Precision',
    accuracyClass: 'Class III (Medium Accuracy)',
    maxCapacity: '30 kg',
    minCapacity: '100 g',
    verificationDivision: '2 g (e)',
    location: 'Plot 42, Okhla Industrial Area Phase-III, New Delhi - 110020',
    scheduledDate: '2026-09-19',
    timeSlot: '11:00 AM - 12:30 PM',
    priority: 'NORMAL',
    riskScore: 14,
    status: 'PENDING',
    assignedInspector: 'Insp. Vikram Sharma (Badge: DL-LM-INS-985)',
    targetGps: {
      lat: 28.5355,
      lng: 77.2680,
      address: 'Plot 42, Okhla Industrial Area Phase-III, New Delhi - 110020',
      geofenceRadiusMeters: 50
    },
    standardWeightsRequired: 'Class M1 Standard Weights (5kg, 10kg, 20kg calibrated blocks)',
    checklist: {
      instrumentAvailable: true,
      serialNumberVisible: true,
      manufacturerDetailsVisible: true,
      displayFunctioning: true,
      requiredMarkingsVisible: true,
      requiredDocumentsAvailable: true
    },
    testReadings: [
      { testWeight: '5 kg Class M1 Standard', loadKg: 5, readingKg: 5.000, errorG: 0, toleranceG: 5, result: 'PASS' },
      { testWeight: '15 kg Class M1 Standard', loadKg: 15, readingKg: 15.001, errorG: 1, toleranceG: 10, result: 'PASS' },
      { testWeight: '30 kg Full Scale Test', loadKg: 30, readingKg: 30.002, errorG: 2, toleranceG: 15, result: 'PASS' }
    ],
    inspectionReport: null
  }
];

export const MOCK_STATS = {
  business: {
    totalInstruments: 1,
    pendingApplications: 0,
    underInspection: 1,
    approved: 0,
    activeCertificates: 0
  },
  inspector: {
    assignedInspections: 1,
    pendingInspections: 1,
    completedInspections: 0,
    highRiskCases: 0
  },
  officer: {
    pendingApplications: 0,
    highRiskCases: 0,
    underInspection: 1,
    approvedTotal: 0,
    rejectedTotal: 0
  }
};

export const MOCK_REPORTS = [
  {
    id: 'REP-PS-2026-001',
    reportNo: 'METRA-REP-PS-001',
    title: 'Legal Metrology Compliance & Calibration Audit Report',
    userId: 'usr_pushpa_01',
    userEmail: 'PuhspaGOat-singhpushpendra95734@gmail.com',
    userName: 'Pushpendra Singh',
    organization: 'Singh Legal Metrology & Enterprise Tech',
    reportType: 'CALIBRATION_AUDIT',
    overallStatus: 'FULLY_COMPLIANT',
    complianceIndex: '99.4%',
    verifiedInstrumentsCount: 4,
    zeroFaultsDetected: true,
    trustChainBlockHash: '3a8f9c2d1e4b506789abcdef0123456789abcdef0123456789abcdef01234567',
    blockIndex: 8914,
    generatedAt: '2026-09-08',
    summary: 'All 4 operational instruments validated in full accordance with Legal Metrology (General) Rules 2011.'
  },
  {
    id: 'REP-PS-2026-002',
    reportNo: 'METRA-REP-PS-002',
    title: 'Real-time Field Telematics & Geofence Verification Report',
    userId: 'usr_pushpa_01',
    userEmail: 'PuhspaGOat-singhpushpendra95734@gmail.com',
    userName: 'Pushpendra Singh',
    organization: 'Singh Legal Metrology & Enterprise Tech',
    reportType: 'TELEMATICS_INSPECTION',
    inspector: 'Insp. Vikram Singh (INSP-NZ-4082)',
    gpsLock: '28.6139° N, 77.2090° E',
    geofenceDeviationMeters: 3.4,
    antiSpoofingStatus: 'VERIFIED_GENUINE_HARDWARE',
    signalIntegrity: '100%',
    generatedAt: '2026-09-05',
    summary: 'On-site presence confirmed within 3.4m of registered enterprise site in Sector 18, New Delhi.'
  },
  {
    id: 'REP-PS-2026-003',
    reportNo: 'METRA-REP-PS-003',
    title: 'Maximum Permissible Error (MPE) Multi-Point Accuracy Analysis',
    userId: 'usr_pushpa_01',
    userEmail: 'PuhspaGOat-singhpushpendra95734@gmail.com',
    userName: 'Pushpendra Singh',
    organization: 'Singh Legal Metrology & Enterprise Tech',
    reportType: 'MPE_ACCURACY_ANALYSIS',
    targetInstrument: 'PS-SN-9573401 (PM-DS-95734)',
    testStages: [
      { load: '10 kg', mpeTolerance: '±5 g', observedError: '0 g', status: 'PASS' },
      { load: '30 kg', mpeTolerance: '±10 g', observedError: '+1 g', status: 'PASS' },
      { load: '60 kg', mpeTolerance: '±15 g', observedError: '+2 g', status: 'PASS' }
    ],
    meanRelativeError: '+0.0018%',
    eccentricityCheck: 'PASSED (0.2g max variation)',
    repeatabilitySpread: '0.1g spread across 10 trials',
    generatedAt: '2026-09-05'
  },
  {
    id: 'REP-PS-2026-004',
    reportNo: 'METRA-REP-PS-004',
    title: 'Blockchain Ledger Immutability & Custody Audit Trail',
    userId: 'usr_pushpa_01',
    userEmail: 'PuhspaGOat-singhpushpendra95734@gmail.com',
    userName: 'Pushpendra Singh',
    organization: 'Singh Legal Metrology & Enterprise Tech',
    reportType: 'BLOCKCHAIN_AUDIT_TRAIL',
    merkleRoot: '99f8d1c7e6b5a43210fedcba9876543210fedcba9876543210fedcba98765432',
    totalBlocksInEpoch: 1042,
    publicVerificationHits: 158,
    tamperAttemptsPrevented: 0,
    cryptographicSignature: 'ECDSA_SECP256K1_VERIFIED',
    generatedAt: '2026-09-08'
  },
  {
    id: 'REP-PS-2026-005',
    reportNo: 'METRA-REP-PS-005',
    title: 'Annual Statutory Metrology Portfolio & Renewal Schedule',
    userId: 'usr_pushpa_01',
    userEmail: 'PuhspaGOat-singhpushpendra95734@gmail.com',
    userName: 'Pushpendra Singh',
    organization: 'Singh Legal Metrology & Enterprise Tech',
    reportType: 'STATUTORY_PORTFOLIO',
    activeLicenses: ['07AAAPS95734Z1'],
    totalPaidFees: '₹15,000.00',
    nextScheduledRenewal: '05 September 2027',
    riskRating: 'TIER_1_EXEMPLARY',
    generatedAt: '2026-09-08'
  }
];

